
// Opciones predefinidas
export const CLASES_PALABRA = [
  "sustantivo", "adjetivo", "verbo", "adverbio", "interjección",
  "preposición", "conjunción", "artículo", "pronombre",
  "locución sustantiva", "locución adjetiva", "locución verbal",
  "locución adverbial", "prefijo", "sufijo"
];

export const CLASIFICACIONES_ONTOLOGICAS = [
  "Agrado, placer y alegría",
  "Agricultura",
  "Agua dulce",
  "Agujeros, huecos y aberturas",
  "Alcoholismo",
  "Alfarería",
  "Algas, hongos y vegetales inferiores",
  "Algebra",
  "Alimentación",
  "Alimentos elaborados o cocinados",
  "Amable, educado y simpático / descortesía, rudeza y antipático",
  "Análisis",
  "Anatomía",
  "Anatomía animal comparada con la humana",
  "Anatomía exclusivamente animal",
  "Anatomía vegetal",
  "Animales",
  "Antropología",
  "Matemáticas",
  "Mantenerse y durar / consumir y extinguir",
  "Mares y océanos",
  "Materia",
  "Material de escritura y papelería",
  "Materiales de construcción",
  "Materiales y productos de origen animal",
  "Materiales y productos de origen mineral",
  "Materiales y productos de origen vegetal",
  "Mecánica",
  "Medicina",
  "Medios de comunicación",
  "Medios de comunicación de masas",
  "Mejorar y perfeccionar / empeorar y deteriorar",
  "Mestizaje étnico",
  "Metodología científica",
  "Métrica",
  "Metrología",
  "Microbiología",
  "Miedo y peligro",
  "Minerales",
  "Minería",
  "Misterios y secretos",
  "Mitos y fábulas",
  "Mobiliario, menaje y decoración",
  "Modos de pronunciar",
  "Molinero",
  "Molinos de viento",
  "Moralidad, justicia y equidad / inmoralidad e injusticia",
  "Mostrar, manifestar y difundir",
  "Moverse a pie",
  "Movimiento",
  "Movimiento de fluidos",
  "Música",
  "Navegación",
  "Negocios y empresas",
  "No acción",
  "Nombres propios",
  "Normal, común y frecuente / extraordinario e infrecuente",
  "Números",
  "Objetos metálicos",
  "Obligaciones, contratos y acuerdos",
  "Ocio y diversión",
  "Ociosidad y negligencia",
  "Oponer o estar en contra",
  "Óptica",
  "Organización social",
  "Organización territorial",
  "Organizaciones e instituciones",
  "Orgullo / modestia",
  "Ortografía, letras y alfabetos",
  "Otras adicciones",
  "Otras profesiones",
  "Otros productos vegetales",
  "Paleontología",
  "Peces",
  "Pedagogía y enseñanza",
  "Pedir, conceder y denegar",
  "Peleas de gallos",
  "Peletería",
  "Pensamiento, entendimiento y voluntad",
  "Pensamiento, juicio y opinión",
  "Perjuicio, daño y desamparo",
  "Pesca",
  "Peso",
  "Piezas y partes de cosas",
  "Plantas",
  "Poder legislativo",
  "Política",
  "Poner, colgar y apoyar / quitar",
  "Posesión / carencia",
  "Posibilidad / imposibilidad",
  "Posturas y movimientos corporales",
  "Potencia y eficacia",
  "Precisión y exactitud / vaguedad",
  "Prensa",
  "Preparación y características de los alimentos",
  "Preparación y planificación",
  "Presencia y manifestación",
  "Presencia, reunión y compañía / ausencia y soledad",
  "Probabilidad y estadísticas",
  "Problemas y dificultades",
  "Procedimientos, actuaciones y resoluciones judiciales",
  "Procesos y reacciones",
  "Producir y elaborar",
  "Productos metálicos",
  "Productos químicos",
  "Profesiones",
  "Profesores y alumnos",
  "Protección civil y otros cuerpos de seguridad",
  "Protección, favor, seguridad y cuidado",
  "Psicología",
  "Publicidades",
  "Querer y desear",
  "Radio, televisión y cine",
  "Realidad y existencia",
  "Recuerdo y memoria / olvido",
  "Relación",
  "Relación del hombre con los animales",
  "Relacionar, corresponder y comparar",
  "Relaciones amorosas",
  "Relaciones familiares",
  "Relaciones sociales",
  "Religión",
  "Reptiles",
  "Restauración",
  "Ropa"
];
